### ISSUE TITLE
HLS video with wide pixel doesn't scale in Chrome 71

### ISSUE THREAD

**Issue by gtx5200ultra** [videojs/http-streaming#312]
## Description
HLS video stream with custom pixel size (not square) doesn't play correct on latest Chrome browser
It works fine on previous versions or in different browsers

## Steps to reproduce

1. Open HLS stream with non-square pixels size

![screenshot_116](https://user-images.githubusercontent.com/9646751/49889846-9fb54d80-fe53-11e8-81ae-7767a03c18a9.png)

2. See that video should be stretched to full window size, like in example below (because of pixel size, original video stream size 720x576 with wide pixel). Screenshot made in Edge

![screenshot_117](https://user-images.githubusercontent.com/9646751/49889842-9d52f380-fe53-11e8-8b2b-0a5bd78d8a1e.png)

## Additional Information
Works fine with videojs player if open local video file. Reproduces only on hls streams.

### videojs-http-streaming version
videojs-http-streaming 1.5.1

### videojs version
video.js 7.3.0

### Browsers
Version 71.0.3578.80 (Official Build) (64-bit)

* Due the service restrictions, we are not available to provide test stream at this moment. If needed, we can think about it

```
<head>
  <link href="https://vjs.zencdn.net/7.3.0/video-js.css" rel="stylesheet">
  <script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>
  <script src="videojs-http-streaming.min.js"></script>
</head>
<body>
  <video id="my-video" class="video-js" controls preload="auto" data-setup="{}">
    <source src="..." type="application/x-mpegURL">
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
  <script src="https://vjs.zencdn.net/7.3.0/video.js"></script>
</body>
```

**Comment by forbesjo** [comment]
We'll need a test stream in order to investigate this bug, it would be great if you could provide a sample

**Comment by gtx5200ultra** [comment]
Test stream: http://91.224.186.14:8200/hls/2097/index.m3u8

**Comment by thecotne** [comment]
@forbesjo any ETA on this?

**Comment by thecotne** [comment]
so this is code in question https://github.com/videojs/mux.js/blob/master/lib/mp4/mp4-generator.js#L428-L434

```js
0x00, 0x00, 0x00, 0x00, // pre_defined 
(track.width & 0xff00) >> 8, 
track.width & 0xff, // width 
(track.height & 0xff00) >> 8, 
track.height & 0xff, // height 
0x00, 0x48, 0x00, 0x00, // horizresolution 
0x00, 0x48, 0x00, 0x00, // vertresolution 
```

and this is same function in hlsjs which does not have this bug https://github.com/video-dev/hls.js/blob/master/src/remux/mp4-generator.js#L373-L379

```js
0x00, 0x00, 0x00, 0x00, // pre_defined
(width >> 8) & 0xFF,
width & 0xff, // width
(height >> 8) & 0xFF,
height & 0xff, // height
0x00, 0x48, 0x00, 0x00, // horizresolution
0x00, 0x48, 0x00, 0x00, // vertresolution
```

@forbesjo can we just use hlsjs version? can't it have some unwanted side effects?

**Comment by thecotne** [comment]
test stream https://www.mediafire.com/file/u7mzg27sb49ym4d/test-stream.zip/file

**Comment by jackwpearson** [comment]
@forbesjo is there a fix in the works for this bug? seeing this in Chrome as well just like the images referenced in the original bug report above.  Thanks!

**Comment by woellij** [comment]
looking forward to this PR getting merged. causing a lot of issues

https://github.com/videojs/http-streaming/issues/551 is related i think

**Comment by elpiojo86** [comment]
When can we expect this merge? Seems to be affecting quite a few people! Thanks!

**Comment by sebst3r** [comment]
I have the exact same issue and am looking forward very much to get this fixed! Pls fix.

**Comment by SebKei** [comment]
Issue still present with videojs 7.60 and Chrome 76.
When will this be fixed?

**Comment by emkman99** [comment]
Just waiting for https://github.com/videojs/mux.js/pull/275 to be added in mux.js.

@SebKei If you need it fixed now, then you'll have to build it yourself. I'm currently using https://github.com/videojs/video.js/tree/7.5.x, http-streaming v1.10.3, and https://github.com/emkman99/mux.js.

**Comment by SebKei** [comment]
@emkman99 Thank you for the info, but unfortunately building it myself is currently no option for my project. So I hope your fix gets merged soon!

**Comment by MathijsV** [comment]
This same bug still occurs with non-square pixels in Chrome (mobile and desktop) when using fragmented MP4 (fMP4) HLS streams. Example stream: http://89.41.171.52/rn7live_abr_fmp4/tv/playlist.m3u8
This should display as 16:9 and it does in every browser except Chrome. In Chrome this displays as 4:3.

**Comment by woellij** [comment]
Oh ipad this gives us a green strip to the sides now. video.js 7.3.3

**Comment by Mariare2** [comment]
For some particular reason I am still working with video.js 6+. Is There a way to fix this on the earlier versions of video.js? Any hints on how to do that?
I tried changing the code @thecotne mentioned in mux.js, but it didn't help.

Thank you!

**Comment by gkatsev** [comment]
You can probably use VHS with Video.js 6.

**Comment by Mariare2** [comment]
> You can probably use VHS with Video.js 6.

Thank you for your answer, I just updated mux.js and it worked.
